
name: Deploy

on:
  # Trigger when "Build" workflow run is completed
  workflow_run:
    workflows: [ Build ]
    types:
      - completed

  # Push to main
  push:
    branches: [ main ]

  # Manually triggered
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Login to ACR'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME=${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/simplychat-chatservice-apis-rest
        IMAGE_TAG=${{ github.sha }}
        APP_DIR=src/Apps/ChatService.APIs.REST

        echo "Building Docker image..."
        docker build \
          -f $APP_DIR/Dockerfile \
          -t $IMAGE_NAME:$IMAGE_TAG \
          $APP_DIR

        echo "Pushing Docker image..."
        docker push $IMAGE_NAME:$IMAGE_TAG

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.SIMPLYCHAT_RG_NAME }}
        template: ./deploy/azure/bicep/main.bicep
        parameters: |
          environmentName=dev
          restApiContainerImage=${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/simplychat-chatservice-apis-rest:${{ github.sha }}
          registryServer=${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          registryUsername=${{ secrets.AZURE_REGISTRY_USERNAME }}
          registryPassword=${{ secrets.AZURE_REGISTRY_PASSWORD }}
        failOnStdErr: false